---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: lms
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: registry.jetbrains.team/p/edu/containers/lms
      ko: {} # Go build with ko, see skaffold docs for more
  local:
    useDockerCLI: false
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: go-web-app
        remoteChart: oci://registry.jetbrains.team/p/cb/helm-charts/simple-app # You can leave it or specify any your helm chart or from your repo
        version: 0.2.0
        artifactOverrides:
          image: registry.jetbrains.team/p/ksk/containers/go-web-app # Must match you container image path from Space
        setValueTemplates:
          imagePullSecret: "{{.IMAGE_PULL_SECRET}}"
          applicationName: "{{.APPLICATION_NAME}}"
        valuesFiles:
          - values.yaml
