# Generated by Django 3.2.18 on 2023-12-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('study_programs', '0003_auto_20210322_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdiscipline',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sites.site', verbose_name='Site'),
        ),
    ]
