# Generated by Django 3.2.18 on 2024-04-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0005_alter_academicdiscipline_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdiscipline',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='academicdiscipline',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='academicdiscipline',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='academicdiscipline',
            name='name_ru',
        ),
    ]
