# Generated by Django 4.2.18 on 2025-03-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study_programs", "0006_auto_20240425_1356"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studyprogram",
            name="branch",
        ),
    ]
