# Generated by Django 4.2.18 on 2025-03-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0002_city_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="university",
        ),
        migrations.RemoveField(
            model_name="university",
            name="city",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="Faculty",
        ),
        migrations.DeleteModel(
            name="University",
        ),
    ]
