# Generated by Django 3.2.18 on 2023-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0043_studentgroupteacherbucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='first_student_comment_at',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='last_comment_from',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='meta',
        ),
        migrations.AlterField(
            model_name='enrollmentperiod',
            name='ends_on',
            field=models.DateField(blank=True, help_text='Inclusive. Leave blank to calculate based on a default duration (45 days)', null=True, verbose_name='Closing Day'),
        ),
    ]
