# Generated by Django 3.2.18 on 2023-12-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0044_auto_20231227_1106'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollmentperiod',
            name='unique_enrollment_period_per_semester_per_site',
        ),
        migrations.RemoveField(
            model_name='enrollmentperiod',
            name='site',
        ),
    ]
