# Generated by Django 3.2.18 on 2024-01-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0045_auto_20231227_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentscoreauditlog',
            name='source',
            field=models.CharField(choices=[('api', 'REST API'), ('csv-enrollment', 'Imported from CSV by LMS Student ID'), ('admin', 'Admin Panel'), ('form', 'Form on Assignment Detail Page'), ('gradebook', 'Gradebook'), ('webhook-gerrit', 'Gerrit Webhook')], max_length=15, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='enrollmentgradelog',
            name='source',
            field=models.CharField(choices=[('gradebook', 'Gradebook'), ('csv-enrollment', 'Imported from CSV by LMS Student ID'), ('admin', 'Admin Panel')], max_length=15, verbose_name='Source'),
        ),
    ]
