# Generated by Django 3.2.18 on 2024-03-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0046_auto_20240116_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateprofile',
            name='diploma_issued_on',
        ),
        migrations.RemoveField(
            model_name='graduateprofile',
            name='diploma_number',
        ),
        migrations.RemoveField(
            model_name='graduateprofile',
            name='diploma_registration_number',
        ),
    ]
