# Generated by Django 3.2.18 on 2024-05-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_remove_course_grading_type'),
        ('learning', '0048_auto_20240425_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='course_program_binding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseprogrambinding'),
        ),
    ]
