# Generated by Django 3.2.18 on 2024-05-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0049_enrollment_course_program_binding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='branch',
        ),
    ]
