# Generated by Django 3.2.18 on 2024-04-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0051_delete_enrollmentperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='name_ru',
        ),
    ]
