# Generated by Django 3.2.18 on 2024-05-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0050_remove_invitation_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollmentPeriod',
        ),
    ]
