# Generated by Django 3.2.18 on 2024-06-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20240425_1356'),
        ('learning', '0051_auto_20240425_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='invitation',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.academicprogram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='program_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.academicprogramrun', verbose_name='Program run'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('manual', 'Manual'), ('program', 'Program'), ('program_run', 'Program run')], default='program', max_length=100, verbose_name='Group Type'),
        ),
    ]
