# Generated by Django 4.2.13 on 2024-07-04 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0052_auto_20240606_1642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentassignment",
            name="watchers",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student Assignment Watchers",
            ),
        ),
        migrations.DeleteModel(
            name="GraduateProfile",
        ),
    ]
