# Generated by Django 4.2.13 on 2024-07-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0053_alter_studentassignment_watchers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollmentgradelog",
            options={"verbose_name_plural": "Grade Change Log"},
        ),
    ]
