# Generated by Django 4.2.13 on 2024-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0054_alter_enrollmentgradelog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("not_submitted", "Not submitted"),
                    ("on_checking", "On checking"),
                    ("need_fixes", "Need fixes"),
                    ("completed", "Completed"),
                ],
                default="not_submitted",
                max_length=13,
                verbose_name="StudentAssignment|Status",
            ),
        ),
    ]
