# Generated by Django 4.2.13 on 2024-08-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_remove_course_branches'),
        ('learning', '0055_alter_studentassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course_program_binding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.courseprogrambinding'),
        ),
    ]
