# Generated by Django 4.2.14 on 2024-09-09 10:27

from django.db import migrations, models
import django.db.models.deletion
from markupsafe import Markup


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_location_description"),
        ("learning", "0056_alter_enrollment_course_program_binding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True,
                help_text=Markup(
                    'Read how to style the text <a href="/commenting-the-right-way/" target="_blank">here</a>. HTML is partially enabled too.'
                ),
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.location",
                verbose_name="Venue",
            ),
        ),
    ]
