# Generated by Django 4.2.14 on 2024-10-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0061_remove_courseprogrambinding_one_course_run_per_program_and_more",
        ),
        ("learning", "0057_alter_event_description_alter_event_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="invitation",
        ),
        migrations.AlterField(
            model_name="invitation",
            name="courses",
            field=models.ManyToManyField(
                through="courses.CourseProgramBinding",
                to="courses.course",
                verbose_name="Courses",
            ),
        ),
        migrations.DeleteModel(
            name="CourseInvitation",
        ),
    ]
