# Generated by Django 4.2.14 on 2024-12-23 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0058_remove_enrollment_invitation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentcomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
    ]
