# Generated by Django 4.2.14 on 2025-01-03 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0059_alter_assignmentcomment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentscoreauditlog",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Changed by",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentscoreauditlog",
            name="source",
            field=models.CharField(
                choices=[
                    ("api", "REST API"),
                    ("csv-enrollment", "Imported from CSV by LMS Student ID"),
                    ("admin", "Admin Panel"),
                    ("form", "Form on Assignment Detail Page"),
                    ("gradebook", "Gradebook"),
                    ("webhook-gerrit", "Gerrit Webhook"),
                    ("jba-submission", "JetBrains Academy Submission"),
                ],
                max_length=15,
                verbose_name="Source",
            ),
        ),
    ]
