# Generated by Django 4.2.18 on 2025-03-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0060_alter_assignmentscoreauditlog_changed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="branch",
        ),
    ]
