# Generated by Django 3.2.18 on 2023-12-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0018_remove_siteconfiguration_lms_subdomain'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='siteconfiguration',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site'),
        ),
    ]
