# Generated by Django 3.2.18 on 2024-01-11 14:15

from django.db import migrations
from core.models import City
from core.models import University


def insert_initial_data(apps, schema_editor):
    bremen = City()
    bremen.code = 'BRE'
    bremen.name = 'Bremen'
    bremen.abbr = 'Bremen'
    bremen.time_zone = 'Europe/Berlin'
    bremen.save()

    paphos = City()
    paphos.code = 'PFO'
    paphos.abbr = 'Pafos'
    paphos.name = 'Pafos'
    paphos.time_zone = 'Asia/Nicosia'
    paphos.save()

    cub = University()
    cub.name = 'Constructor University Bremen'
    cub.abbr = 'CUB'
    cub.city = bremen
    cub.save()

    nup = University()
    nup.name = 'Neapolis University Pafos'
    nup.abbr = 'NUP'
    nup.city = paphos
    nup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20231227_1106'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
