# Generated by Django 3.2.18 on 2024-01-11 15:46

import core.db.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0020_auto_20240111_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='time_zone',
            field=core.db.fields.TimeZoneField(choices=[('Europe/Berlin', 'Europe/Berlin'), ('Europe/Kiev', 'Europe/Kiev'), ('Europe/Moscow', 'Europe/Moscow'), ('Europe/Minsk', 'Europe/Minsk'), ('Asia/Nicosia', 'Asia/Nicosia'), ('Asia/Yekaterinburg', 'Asia/Yekaterinburg'), ('Asia/Novosibirsk', 'Asia/Novosibirsk')], verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='city',
            name='time_zone',
            field=core.db.fields.TimeZoneField(choices=[('Europe/Berlin', 'Europe/Berlin'), ('Europe/Kiev', 'Europe/Kiev'), ('Europe/Moscow', 'Europe/Moscow'), ('Europe/Minsk', 'Europe/Minsk'), ('Asia/Nicosia', 'Asia/Nicosia'), ('Asia/Yekaterinburg', 'Asia/Yekaterinburg'), ('Asia/Novosibirsk', 'Asia/Novosibirsk')], verbose_name='Timezone'),
        ),
    ]
