# Generated by Django 3.2.18 on 2024-01-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20240111_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('code', models.TextField(verbose_name='Code')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='core.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'AcademicProgram',
                'verbose_name_plural': 'AcademicPrograms',
            },
        ),
        migrations.CreateModel(
            name='AcademicProgramRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(verbose_name='StartYear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='core.academicprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'AcademicProgramRun',
                'verbose_name_plural': 'AcademicProgramRuns',
            },
        ),
    ]
