# Generated by Django 3.2.18 on 2024-01-16 13:27

from django.db import migrations
from core.models import University, AcademicProgram, AcademicProgramRun

def insert_initial_data(apps, schema_editor):
    bremen = University.objects.get(abbr='CUB')

    cub001 = AcademicProgram()
    cub001.title = 'Software, Data and Technology'
    cub001.code = 'CUB-001'
    cub001.university = bremen
    cub001.save()

    cub001run2024 = AcademicProgramRun()
    cub001run2024.start_year = 2024
    cub001run2024.program = cub001
    cub001run2024.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_academicprogram_academicprogramrun'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
