# Generated by Django 3.2.18 on 2024-01-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_branch_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='lms_domain',
        ),
    ]
