# Generated by Django 3.2.18 on 2024-04-05 10:51

import core.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_siteconfiguration_lms_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='time_zone',
            field=core.db.fields.TimeZoneField(verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='city',
            name='time_zone',
            field=core.db.fields.TimeZoneField(verbose_name='Timezone'),
        ),
    ]
