# Generated by Django 3.2.18 on 2024-04-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_branch_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='city',
            name='abbr_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='abbr_ru',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_ru',
        ),
    ]
