# Generated by Django 4.2.14 on 2024-09-09 10:27

from django.db import migrations, models
from markupsafe import Markup


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_auto_20240425_1356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="description",
            field=models.TextField(
                help_text=Markup(
                    'Read how to style the text <a href="/commenting-the-right-way/" target="_blank">here</a>. HTML is partially enabled too.'
                ),
                verbose_name="Description",
            ),
        ),
    ]
