# Generated by Django 4.2.18 on 2025-03-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_location_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alumni_chat_link",
                    models.CharField(blank=True, verbose_name="Alumni chat link"),
                ),
            ],
            options={
                "verbose_name": "Config",
                "verbose_name_plural": "Config",
            },
        ),
        migrations.AddConstraint(
            model_name="config",
            constraint=models.CheckConstraint(
                check=models.Q(("id", 1)), name="config_unique"
            ),
        ),
    ]
