# Generated by Django 4.2.18 on 2025-03-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0068_delete_coursebranch"),
        ("study_programs", "0007_remove_studyprogram_branch"),
        (
            "users",
            "0069_remove_studentprofile_unique_regular_student_per_admission_campaign_and_more",
        ),
        ("learning", "0061_remove_event_branch"),
        ("core", "0030_config_config_config_unique"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Branch",
        ),
    ]
