# Generated by Django 3.2.18 on 2024-01-25 16:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_branch_site'),
        ('courses', '0043_auto_20231227_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgramBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_end_date', models.DateField()),
                ('grading_system_num', models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Pass/Fail'), (3, 'Pass/Fail + Excellent'), (2, '10-point scale')], default=0, verbose_name='Grading system for the students from the associated program')),
                ('start_year_filter', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='courses.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.academicprogram')),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseprogrambinding',
            constraint=models.UniqueConstraint(fields=('course', 'program'), name='one_course_run_per_program'),
        ),
    ]
