# Generated by Django 3.2.18 on 2024-01-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20240111_1546'),
        ('courses', '0045_auto_20240125_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='main_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.branch', verbose_name='Main Branch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='completed_at',
            field=models.DateField(blank=True, help_text='Consider the course as completed from the specified day (inclusive).', null=True, verbose_name='Date of completion'),
        ),
    ]
