# Generated by Django 3.2.18 on 2024-01-11 10:47
from datetime import timedelta

import pytz
from django.db import migrations
from courses.constants import SemesterTypes
from courses.utils import TermPair
from learning.settings import GradingSystems

def add_test_data(apps, schema_editor):
    AcademicProgram = apps.get_model('core', 'AcademicProgram')
    Semester = apps.get_model('courses', 'Semester')
    MetaCourse = apps.get_model('courses', 'MetaCourse')
    Course = apps.get_model('courses', 'Course')
    CourseProgramBinding = apps.get_model('courses', 'CourseProgramBinding')

    spring2024 = Semester()
    spring2024.year = 2024
    spring2024.type = SemesterTypes.SPRING
    term_pair = TermPair(spring2024.year, spring2024.type)
    next_term = term_pair.get_next()
    tz = pytz.UTC
    spring2024.index = term_pair.index
    spring2024.starts_at = term_pair.starts_at(tz)
    spring2024.ends_at = next_term.starts_at(tz) - timedelta(days=1)
    spring2024.save()

    courseMT = MetaCourse()
    courseMT.name = 'Multiplication Tables'
    courseMT.slug = 'multiplication-tables'
    courseMT.short_description = 'We will learn how to multiply integer numbers'
    courseMT.save()

    courseRun = Course()
    courseRun.meta_course = courseMT
    courseRun.semester = spring2024
    courseRun.completed_at = '2024-05-31'
    courseRun.save()

    cub001_program = AcademicProgram.objects.get(code='CUB-001')
    courseMT_at_cub001 = CourseProgramBinding()
    courseMT_at_cub001.course = courseRun
    courseMT_at_cub001.program = cub001_program
    courseMT_at_cub001.enrollment_end_date = '2024-02-15'
    courseMT_at_cub001.grading_system_num = GradingSystems.TEN_POINT
    courseMT_at_cub001.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_alter_course'),
        ('learning', '0038_auto_20220215_0715')
    ]

    operations = [
        migrations.RunPython(add_test_data)
    ]
