# Generated by Django 3.2.18 on 2024-02-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_siteconfiguration_lms_domain'),
        ('courses', '0047_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='main_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.branch', verbose_name='Main Branch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='group_mode',
            field=models.CharField(choices=[('no_groups', 'No Groups'), ('manual', 'Manual'), ('branch', 'Branches'), ('invite_and_branch', 'Invitations and Branches')], default='manual', help_text='Choose `Branch` to auto generate student groups from course branches.', max_length=100, verbose_name='Student Group Mode'),
        ),
        migrations.RemoveField(
            model_name='learningspace',
            name='branch',
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_for_main_branch_in_a_term',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('meta_course', 'semester'), name='unique_course_in_a_term'),
        ),
    ]
