# Generated by Django 3.2.18 on 2024-04-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_shut_down_course_main_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grading_type',
            field=models.SmallIntegerField(choices=[(1, 'Pass/Fail'), (3, 'Pass/Fail + Excellent'), (0, '5-point scale'), (2, '10-point scale'), (4, '100-point scale')], default=0, verbose_name='CourseOffering|grading_type'),
        ),
        migrations.AlterField(
            model_name='courseprogrambinding',
            name='grading_system_num',
            field=models.SmallIntegerField(choices=[(1, 'Pass/Fail'), (3, 'Pass/Fail + Excellent'), (0, '5-point scale'), (2, '10-point scale'), (4, '100-point scale')], default=0, verbose_name='Grading system for the students from the associated program'),
        ),
    ]
