# Generated by Django 3.2.18 on 2024-05-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_auto_20240418_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grading_type',
        ),
    ]
