# Generated by Django 3.2.18 on 2024-05-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_remove_course_grading_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('online', 'Online Submission'), ('external', 'External Service'), ('penalty', 'Penalty'), ('other', 'No Submission')], max_length=42, verbose_name='Assignment Format'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube links are supported', max_length=512, verbose_name='Video Recording'),
        ),
    ]
