# Generated by Django 3.2.18 on 2024-05-31 15:25

import core.db.fields
import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_auto_20240516_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_zone',
            field=core.db.fields.TimeZoneField(blank=True, default=courses.models.get_course_default_timezone, null=True, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], db_index=True, default='en', help_text='The language in which lectures are given.', max_length=5, verbose_name='Language'),
        ),
    ]
