# Generated by Django 3.2.18 on 2024-04-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_auto_20240531_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='metacourse',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='metacourse',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='metacourse',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='metacourse',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='metacourse',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='metacourse',
            name='short_description_ru',
        ),
    ]
