# Generated by Django 3.2.18 on 2024-04-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_auto_20240425_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
    ]
