# Generated by Django 3.2.18 on 2024-05-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_remove_course_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='passing_score',
        ),
    ]
