# Generated by Django 3.2.18 on 2024-06-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_remove_assignment_passing_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='main_branch',
        ),
    ]
