# Generated by Django 3.2.18 on 2024-06-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_remove_course_main_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group_mode',
            field=models.CharField(choices=[('no_groups', 'No Groups'), ('manual', 'Manual'), ('program', 'Program'), ('program_run', 'Program run')], default='manual', help_text='Choose `Branch` to auto generate student groups from course branches.', max_length=100, verbose_name='Student Group Mode'),
        ),
    ]
