# Generated by Django 4.2.13 on 2024-07-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0057_alter_course_group_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="online_course_url",
        ),
        migrations.RemoveField(
            model_name="course",
            name="survey_url",
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Has lower priority than student group assignees",
                related_name="+",
                to="courses.courseteacher",
                verbose_name="Assignment Assignees",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="group_mode",
            field=models.CharField(
                choices=[
                    ("no_groups", "No Groups"),
                    ("manual", "Manual"),
                    ("program", "Program"),
                    ("program_run", "Program run"),
                ],
                default="manual",
                help_text="Program - a group will be generated for each course program binding<br>Program run - a group will be generated for each program run with at least 1 student enrolled to the course",
                max_length=100,
                verbose_name="Student Group Mode",
            ),
        ),
    ]
