# Generated by Django 4.2.13 on 2024-08-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_remove_course_online_course_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branches',
        ),
    ]
