# Generated by Django 4.2.14 on 2024-09-09 10:27

from django.db import migrations, models
from markupsafe import Markup


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0059_remove_course_branches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="text",
            field=models.TextField(
                help_text=Markup(
                    'Read how to style the text <a href="/commenting-the-right-way/" target="_blank">here</a>. HTML is partially enabled too.'
                ),
                verbose_name="Assignment|text",
            ),
        ),
        migrations.AlterField(
            model_name="courseclass",
            name="description",
            field=models.TextField(
                blank=True,
                help_text=Markup(
                    'Read how to style the text <a href="/commenting-the-right-way/" target="_blank">here</a>. HTML is partially enabled too.'
                ),
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="courseclass",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="courseclass",
            name="other_materials",
            field=models.TextField(
                blank=True,
                help_text=Markup(
                    'Read how to style the text <a href="/commenting-the-right-way/" target="_blank">here</a>. HTML is partially enabled too.'
                ),
                verbose_name="CourseClass|Other materials",
            ),
        ),
        migrations.AlterField(
            model_name="coursenews",
            name="text",
            field=models.TextField(
                help_text=Markup(
                    'Read how to style the text <a href="/commenting-the-right-way/" target="_blank">here</a>. HTML is partially enabled too.'
                ),
                verbose_name="CourseNews|text",
            ),
        ),
        migrations.AlterField(
            model_name="coursereview",
            name="text",
            field=models.TextField(
                help_text=Markup(
                    'Read how to style the text <a href="/commenting-the-right-way/" target="_blank">here</a>. HTML is partially enabled too.'
                ),
                verbose_name="CourseReview|text",
            ),
        ),
        migrations.AlterField(
            model_name="learningspace",
            name="description",
            field=models.TextField(
                blank=True,
                help_text=Markup(
                    'Read how to style the text <a href="/commenting-the-right-way/" target="_blank">here</a>. HTML is partially enabled too.'
                ),
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="metacourse",
            name="description",
            field=models.TextField(
                help_text=Markup(
                    'Read how to style the text <a href="/commenting-the-right-way/" target="_blank">here</a>. HTML is partially enabled too.'
                ),
                verbose_name="Course|description",
            ),
        ),
    ]
