# Generated by Django 4.2.14 on 2024-10-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_location_description"),
        ("learning", "0057_alter_event_description_alter_event_name_and_more"),
        (
            "courses",
            "0060_alter_assignment_text_alter_courseclass_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="courseprogrambinding",
            name="one_course_run_per_program",
        ),
        migrations.AddField(
            model_name="courseprogrambinding",
            name="invitation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bindings",
                to="learning.invitation",
            ),
        ),
        migrations.AlterField(
            model_name="courseprogrambinding",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="core.academicprogram",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseprogrambinding",
            constraint=models.UniqueConstraint(
                fields=("course", "program", "invitation"),
                name="one_course_run_per_program_or_invite",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseprogrambinding",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("invitation__isnull", False),
                    ("program__isnull", False),
                    _connector="XOR",
                ),
                name="exactly_one_of_invitation_program",
            ),
        ),
    ]
