# Generated by Django 4.2.14 on 2024-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_remove_courseprogrambinding_one_course_run_per_program_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseprogrambinding',
            name='one_course_run_per_program_or_invite',
        ),
        migrations.AddConstraint(
            model_name='courseprogrambinding',
            constraint=models.UniqueConstraint(fields=('course', 'program'), name='one_course_run_per_program'),
        ),
        migrations.AddConstraint(
            model_name='courseprogrambinding',
            constraint=models.UniqueConstraint(fields=('course', 'invitation'), name='one_course_run_per_invitation'),
        ),
    ]
