# Generated by Django 4.2.14 on 2024-10-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0062_remove_courseprogrambinding_one_course_run_per_program_or_invite_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="public_attachments_count",
        ),
        migrations.RemoveField(
            model_name="course",
            name="public_slides_count",
        ),
        migrations.RemoveField(
            model_name="course",
            name="public_videos_count",
        ),
        migrations.AlterField(
            model_name="course",
            name="materials_visibility",
            field=models.CharField(
                choices=[
                    ("participants", "All Students"),
                    ("private", "Course Participants"),
                ],
                default="private",
                help_text="Default visibility for class materials.",
                max_length=12,
                verbose_name="Materials Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="courseclass",
            name="materials_visibility",
            field=models.CharField(
                choices=[
                    ("participants", "All Students"),
                    ("private", "Course Participants"),
                ],
                help_text="Slides, attachments and other materials",
                max_length=12,
                verbose_name="Materials Visibility",
            ),
        ),
    ]
