# Generated by Django 4.2.14 on 2024-11-01 12:36

import core.timezone.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0063_remove_course_public_attachments_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="opens_at",
            field=core.timezone.fields.TimezoneAwareDateTimeField(
                default=django.utils.timezone.now, verbose_name="Opens at"
            ),
        ),
    ]
