# Generated by Django 4.2.14 on 2024-11-15 19:01

import core.timezone.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0064_assignment_opens_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseprogrambinding",
            name="enrollment_end_date",
            field=core.timezone.fields.TimezoneAwareDateTimeField(
                help_text="In the timezone of the course"
            ),
        ),
    ]
