# Generated by Django 4.2.14 on 2024-12-23 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0065_alter_courseprogrambinding_enrollment_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="jba_course_id",
            field=models.IntegerField(
                blank=True,
                help_text="Can be obtained from a marketplace link, for example<br/>https://plugins.jetbrains.com/plugin/<b>16628</b>-kotlin-koans",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Marketplace Course ID",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("online", "Online Submission"),
                    ("jba", "JetBrains Academy Course"),
                    ("external", "External Service"),
                    ("penalty", "Penalty"),
                    ("other", "No Submission"),
                ],
                max_length=42,
                verbose_name="Assignment Format",
            ),
        ),
    ]
