# Generated by Django 4.2.18 on 2025-01-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0066_assignment_jba_course_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="courseprogrambinding",
            name="exactly_one_of_invitation_program",
        ),
        migrations.AddField(
            model_name="courseprogrambinding",
            name="is_alumni",
            field=models.BooleanField(default=False, verbose_name="Alumni"),
        ),
        migrations.AddConstraint(
            model_name="courseprogrambinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_alumni", True)),
                fields=("course",),
                name="one_course_run_for_alumni",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseprogrambinding",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("invitation__isnull", False),
                    ("program__isnull", False),
                    ("is_alumni", True),
                    _connector="XOR",
                ),
                name="exactly_one_of_invitation_program_alumni",
            ),
        ),
    ]
