# Generated by Django 4.2.18 on 2025-03-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0067_remove_courseprogrambinding_exactly_one_of_invitation_program_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseBranch",
        ),
    ]
