# Generated by Django 3.2.18 on 2023-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_yandexuserdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='index_redirect',
            field=models.CharField(blank=True, choices=[('projects', 'Проекты'), ('learning', 'Обучение'), ('teaching', 'Преподавание'), ('staff', 'Курирование')], max_length=200, verbose_name='Index Redirect Option'),
        ),
        migrations.AlterField(
            model_name='user',
            name='private_contacts',
            field=models.TextField(blank=True, help_text='LaTeX+Markdown is enabled; will be shown only to logged-in users', verbose_name='Contact information'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_networks',
            field=models.TextField(blank=True, help_text='LaTeX+Markdown is enabled; will be shown to curators only', null=True, verbose_name='Social Networks'),
        ),
    ]
