# Generated by Django 3.2.18 on 2023-12-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20231227_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stepic_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yandex_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yandex_login_normalized',
        ),
    ]
