# Generated by Django 3.2.18 on 2023-12-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20231227_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YandexUserData',
        ),
    ]
