# Generated by Django 3.2.18 on 2024-01-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_academicprogram_academicprogramrun'),
        ('users', '0042_delete_yandexuserdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_program_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.academicprogramrun', verbose_name='ProgramEnrollment'),
        ),
    ]
