# Generated by Django 3.2.18 on 2024-01-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_user_academic_program_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shadcourserecord',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='shadcourserecord',
            name='student',
        ),
        migrations.DeleteModel(
            name='CertificateOfParticipation',
        ),
        migrations.DeleteModel(
            name='SHADCourseRecord',
        ),
    ]
