# Generated by Django 3.2.18 on 2024-01-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20240119_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='site',
        ),
    ]
