# Generated by Django 3.2.18 on 2024-01-29 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_siteconfiguration_lms_domain'),
        ('users', '0045_remove_studentprofile_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='academic_program_enrollment',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_program_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.academicprogramrun', verbose_name='ProgramEnrollment'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch', verbose_name='Branch'),
        ),
        migrations.CreateModel(
            name='SubmissionForm',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_program_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.academicprogramrun', verbose_name='AcademicProgramRun')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
