# Generated by Django 3.2.18 on 2024-03-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_remove_user_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='anytask_url',
        ),
    ]
