# Generated by Django 3.2.18 on 2024-03-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_remove_user_anytask_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='partner',
        ),
    ]
