# Generated by Django 3.2.18 on 2024-03-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20240322_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='year_of_curriculum',
        ),
    ]
