# Generated by Django 3.2.18 on 2024-03-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_remove_studentprofile_year_of_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=100, verbose_name='LinkedIn Profile'),
        ),
    ]
