# Generated by Django 3.2.18 on 2024-03-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_user_linkedin_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_networks',
        ),
    ]
