# Generated by Django 3.2.18 on 2024-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20240328_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('expelled', 'StudentInfo|Expelled'), ('will_graduate', 'StudentInfo|Will graduate'), ('graduate', 'StudentInfo|Graduate')], max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='studentstatuslog',
            name='status',
            field=models.CharField(choices=[('expelled', 'StudentInfo|Expelled'), ('will_graduate', 'StudentInfo|Will graduate'), ('graduate', 'StudentInfo|Graduate')], max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('expelled', 'StudentInfo|Expelled'), ('will_graduate', 'StudentInfo|Will graduate'), ('graduate', 'StudentInfo|Graduate')], max_length=15, verbose_name='Status'),
        ),
    ]
