# Generated by Django 3.2.18 on 2024-03-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20240328_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='diploma_issued_by',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='diploma_issued_on',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='diploma_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_official_student',
        ),
    ]
