# Generated by Django 3.2.18 on 2024-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20240328_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerTag',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular Student'), ('invited', 'Invited Student')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Graduate'), (5, 'Curator'), (7, 'Interviewer [Admission]'), (9, 'Project reviewer'), (10, 'Curator of projects'), (11, 'Invited User'), (12, 'Service User')], verbose_name='Role'),
        ),
    ]
