# Generated by Django 3.2.18 on 2024-04-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20240328_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='level_of_education_on_admission',
        ),
    ]
