# Generated by Django 3.2.18 on 2024-04-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_remove_studentprofile_level_of_education_on_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='index_redirect',
        ),
    ]
