# Generated by Django 3.2.18 on 2024-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_remove_user_index_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cogniterra_user_id',
            field=models.PositiveIntegerField(help_text='Can be found in the user profile', blank=True, null=True, verbose_name='Cogniterra User ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='jetbrains_account',
            field=models.EmailField(blank=True, max_length=254, verbose_name='JetBrains Account Email'),
        ),
    ]
