# Generated by Django 3.2.18 on 2024-06-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20240612_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Student ID'),
        ),
    ]
