# Generated by Django 4.2.13 on 2024-07-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0060_studentprofile_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("expelled", "StudentInfo|Expelled")],
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="studentstatuslog",
            name="status",
            field=models.CharField(
                choices=[("expelled", "StudentInfo|Expelled")],
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("expelled", "StudentInfo|Expelled")],
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Student"),
                    (2, "Teacher"),
                    (5, "Curator"),
                    (7, "Interviewer [Admission]"),
                    (11, "Invited User"),
                    (12, "Service User"),
                ],
                verbose_name="Role",
            ),
        ),
        migrations.DeleteModel(
            name="OnlineCourseRecord",
        ),
    ]
