# Generated by Django 4.2.13 on 2024-07-31 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0054_alter_enrollmentgradelog_options"),
        ("users", "0061_alter_studentprofile_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_profiles",
                to="learning.invitation",
                verbose_name="Invitation",
            ),
        ),
    ]
