# Generated by Django 4.2.13 on 2024-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0062_alter_studentprofile_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("expelled", "Expelled")],
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="year_of_admission",
            field=models.PositiveSmallIntegerField(verbose_name="Admission year"),
        ),
        migrations.AlterField(
            model_name="studentstatuslog",
            name="status",
            field=models.CharField(
                choices=[("expelled", "Expelled")], max_length=15, verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("expelled", "Expelled")],
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Student"),
                    (2, "Teacher"),
                    (5, "Curator"),
                    (11, "Invited User"),
                ],
                verbose_name="Role",
            ),
        ),
    ]
