# Generated by Django 4.2.14 on 2024-09-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0063_alter_studentprofile_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="LaTeX+Markdown is enabled", verbose_name="Note"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="cogniterra_user_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text='This platform can be used as a verification system in some courses. Please create a profile on <a href="https://cogniterra.org/">https://cogniterra.org/</a> and provide your User ID. You can find it on your profile page.',
                null=True,
                verbose_name="Cogniterra User ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="jetbrains_account",
            field=models.EmailField(
                blank=True,
                help_text='Email linked to your login across all JetBrains tools. If you haven\'t created one before, please register here: <a href="https://account.jetbrains.com/login">https://account.jetbrains.com/login</a>',
                max_length=254,
                verbose_name="JetBrains Account Email",
            ),
        ),
    ]
