# Generated by Django 4.2.14 on 2024-09-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0064_alter_user_bio_alter_user_cogniterra_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionform",
            name="require_student_id",
            field=models.BooleanField(
                default=True,
                help_text='Show required "Student ID" field in the form',
                verbose_name="Require Student ID",
            ),
        ),
    ]
