# Generated by Django 4.2.18 on 2025-02-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0065_submissionform_require_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="alumni_consent",
            field=models.CharField(
                choices=[
                    ("not_set", "Not set"),
                    ("declined", "Declined"),
                    ("accepted", "Accepted"),
                ],
                default="not_set",
                verbose_name="Alumni club consent",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="year_of_graduation",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Graduation year"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("expelled", "Expelled"), ("graduated", "Graduated")],
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular Student"),
                    ("invited", "Invited Student"),
                    ("alumni", "Alumni"),
                ],
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="studentstatuslog",
            name="status",
            field=models.CharField(
                choices=[("expelled", "Expelled"), ("graduated", "Graduated")],
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("expelled", "Expelled"), ("graduated", "Graduated")],
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Student"),
                    (2, "Teacher"),
                    (5, "Curator"),
                    (11, "Invited User"),
                    (12, "Alumni"),
                ],
                verbose_name="Role",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "alumni")),
                fields=("user",),
                name="unique_alumni_profile_per_student",
            ),
        ),
    ]
