# Generated by Django 4.2.18 on 2025-03-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0067_country_city_user_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("expelled", "Expelled"),
                    ("graduated", "Graduated"),
                ],
                default="normal",
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="studentstatuslog",
            name="status",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("expelled", "Expelled"),
                    ("graduated", "Graduated"),
                ],
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("normal", "Normal"),
                    ("expelled", "Expelled"),
                    ("graduated", "Graduated"),
                ],
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.RunSQL(
            sql=[
                "update student_profiles set status = 'normal' where status = ''",
                "update users_studentstatuslog set status = 'normal' where status = ''",
            ],
            reverse_sql=[
                "update student_profiles set status = '' where status = 'normal'",
                "update users_studentstatuslog set status = '' where status = 'normal'",
            ]
        ),
    ]
