# Generated by Django 4.2.18 on 2025-03-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0068_alter_studentprofile_status_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studentprofile",
            name="unique_regular_student_per_admission_campaign",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="user",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="usergroup",
            name="branch",
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "regular")),
                fields=("user", "year_of_admission", "academic_program_enrollment"),
                name="unique_regular_student_per_admission_campaign",
            ),
        ),
    ]
