# Generated by Django 3.2.18 on 2024-01-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('faq', '0002_auto_20231227_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='question',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.site', verbose_name='Site'),
        ),
    ]
