# Generated by Django 3.2.18 on 2024-01-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20240116_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='site',
        ),
        migrations.RemoveField(
            model_name='question',
            name='site',
        ),
    ]
