apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.applicationName }}
                port:
                  number: 4180
  tls:
    - hosts:
        - {{ .Values.domainName }}
      secretName: {{ .Values.tlsSecretName }}
