# Generated by Django 3.2.18 on 2024-01-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('info_blocks', '0003_alter_infoblock_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoblock',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sites.site', verbose_name='Site'),
        ),
    ]
