# Generated by Django 4.2.13 on 2024-07-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info_blocks", "0004_alter_infoblock_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infoblocktag",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
    ]
